### ISSUE TITLE
模糊查询bug

### ISSUE THREAD

**Issue by git2205436513** [ID-WangQiang/ssm#3]
模糊插叙的正确语法如下
select count(*) from books where bookName like '%xxxx%';
但是文件中查找的语法里并没有%的通配符从而导致查询失败
修改之后语法应该如下
select count(*) from books where bookName like "%"#{bookName}"%";

**Comment by ID-WangQiang** [comment]
1、SQL语句中模糊查询的正确语法你说的没错
2、在Mybatis中的Mapper文件里你这么直接拼接会导致查询失败
3、如果这里代码真的查询失败回复一些报错日志谢谢

**Comment by git2205436513** [comment]
1.不是会报错，而是查不出来东西 ，我也不好截图给你，你测一下就知道了
2.select count(*) from books where bookName like "%"#{bookName}"%"; 这是我的查询语句，测试了不会报错，可能你说的其他方式？
3.退一步说，原语句中没有加入通配符%，怎么说也不会是模糊查询吧

**Comment by ID-WangQiang** [comment]
https://mybatis.org/mybatis-3/dynamic-sql.html

**Comment by git2205436513** [comment]
这条语句提供了可选的查找文本功能。如果不传入 “title”，那么所有处于 “ACTIVE” 状态的 BLOG 都会返回；如果传入了 “title” 参数，那么就会对 “title” 一列进行模糊查找并返回对应的 BLOG 结果（细心的读者可能会发现，“title” 的参数值需要包含查找掩码或通配符字符）。

原文不也写了要包含通配符吗？ORZ

**Comment by CN-Wangqiang** [comment]
好像确实是我的错，对不起，bug已改，谢谢大佬提出的问题。
